import { createApp } from 'vue'
// import App from './01_组件的嵌套/App.vue'
// import App from './02_组件的通信-父传子/App.vue'
// import App from './03_组件的通信-子传父/App.vue'
// import App from './04_组件通信_案例练习/App.vue'
// import App from './05_组件插槽_基本使用/App.vue'
// import App from './06_组件插槽_具名插槽/App.vue'
// import App from './07_组件插槽_作用域插槽/App.vue'
// import App from './08_Provide和Injet(了解)/App.vue'
// import App from './09_事件总线的使用(掌握)/App.vue'
// import App from './10_生命周期函数演练/App.vue'
// import App from './11_获取元素组件/App.vue'
// import App from './12_动态组件的使用/App.vue'
// import App from './13_Keep-Alive的使用/App.vue'
// import App from './14_组件的v-model/App.vue'
import App from './15_组件的混入mxiin(了解)/App.vue'

createApp(App).mount('#app')
